name: 'Deploy Pipeline'
run-name: Deploy to AWS environments by @${{ github.actor }}

on:
  workflow_call:
    inputs:
        # Deploy to development and test should only be to those environments. Staging deploys should succeed to test from before
      environment_name:
        description: "The environment to deploy to (e.g., development, test, staging, production)"
        required: true
        default: "development"
        type: string
      run_terraform_apply:
        description: "Run terraform apply?"
        required: true
        default: false
        type: boolean


permissions:
   # Allow repository checkout
  contents: read
  # Required to get the ID Token that will be used for OIDC
  id-token: write

env:
  aws_region: "eu-west-1"
  aws_oidc_role_arn: "arn:aws:iam::339713083458:role/GitHubOIDCkununuAccessRole"
jobs:
  run-terraform-against-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: kununu/.github/.github/actions/run-terraform-for-environment@kundevops-2897-centralize-workflows
      with:
        environment_name: ${{ inputs.environment_name }}
        run_terraform_apply: ${{ inputs.run_terraform_apply ||  github.ref == 'refs/heads/main' || false }}